### ISSUE TITLE
(too many logs)にカーソルがあるときのagit_diff

### ISSUE THREAD

**Issue by itchyny** [cohama/agit.vim#25]
(too many logs)にカーソルがあるとき、一番上のコミットのagit_diffが表示されているようです。一番下に表示されているコミットのdiffを表示するか、何も表示しないほうがいいと思います。

**Comment by cohama** [comment]
報告ありがとうございます。修正しました。

**Comment by itchyny** [comment]
確認しました。ありがとうございました。
