### ISSUE TITLE
カレントディレクトリのパスにスペースが含まれる場合、開始できない。

### ISSUE THREAD

**Issue by electron226** [cohama/agit.vim#27]
タイトル通りです。
```
:Agit
```
などを実行した際に、カレントディレクトリのパスにスペースが含まれている場合、
```
git: '(スペースの後のパスの文字列)' is not a git command. See 'git --help'.
```
と表示され、正常に開始されません。
パスにスペースが含まれていない場合は正常に動作しました。

OS: Win8.1 x64

**Comment by cohama** [comment]
報告ありがとうございます。修正しました。
