### ISSUE TITLE
Don't detect current directory by `expand('%:p:h)`

### ISSUE THREAD

**Issue by kamichidu** [cohama/agit.vim#31]
I want agit to use current git directory is `getcwd()` not a current file's directory.

**Comment by cohama** [comment]
No. That behavior is fairly useful for me.
You can use `--dir` option like following
```vim
nnoremap x :<C-u>execute 'Agit --dir=' . getcwd()<CR>
```

**Comment by kamichidu** [comment]
Okay, I'll try it!
Thanks for your suggestion.
