### ISSUE TITLE
git.log: head_indexが正しく取得できていない

### ISSUE THREAD

**Issue by wonderful-panda** [cohama/agit.vim#36]
/autoload/agit/git.vim の `s:git.log()` 内で、以下のようなコードでHEADの行を取得しようとしていますが、まちがっているように見えます。(これだとhead_hash内のいずれかの文字がひとつでもあればmatchするのでほとんどの場合0が返る)

```vim
let head_hash = agit#git#exec('rev-parse --short HEAD', self.git_dir)
let head_index = s:find_index(aligned_log, 'match(v:val, "[' . head_hash . ']") >= 0')
```

意図した動作とするためには、head_hashにString.chompをかけた上で、[]をエスケープする必要があると思います。
ただ、個人的にはLocal Changesの行は常に一番上に表示されている方が使いやすい気がします。

**Comment by cohama** [comment]
報告ありがとうございます。
時間あるときに調査します。

**Comment by cohama** [comment]
もともと gitk の仕様と合わせるために実装してたはずなのですが自分でも忘れてました。
オプションを追加して gitk 互換の動作ができるようにしました。

> ただ、個人的にはLocal Changesの行は常に一番上に表示されている方が使いやすい気がします。

自分でもそう思っているのでデフォルトでは一番上になるようにしています。
