### ISSUE TITLE
g:agit_skip_empty_line のタグ重複

### ISSUE THREAD

**Issue by lambdalisue** [cohama/agit.vim#41]
https://github.com/cohama/agit.vim/blob/master/doc/agit.txt#L244

**Comment by cohama** [comment]
報告ありがとうございます。#40 で治りました。

**Comment by lambdalisue** [comment]
あ、気づいておりませんでした。重複報告失礼いたしました。

**Comment by cohama** [comment]
いえいえ、こちらこそ早めに対応できずお手数おかけしました。
