### ISSUE TITLE
gittree can contain characters `-` and `.`, which are not highlighted correctly

### ISSUE THREAD

**Issue by lesguillemets** [cohama/agit.vim#49]
In some (presumably rare -- I found this while browsing a repository called [MetroGit](https://github.com/vbarbaresi/MetroGit)) cases where more than two branches are merged in a commit, `-` and `.` appear in the git graph. Currently they are not properly highlighted: 

![agitbug](https://cloud.githubusercontent.com/assets/5000967/8632291/a3ae7f78-27cf-11e5-9acd-b448abfdd4e0.png)

A script for reproduction (please execute in an empty directory if you do):

```bash
#!/bin/bash
# execute in an empty directory 
git init
touch "i"
git add .
git commit -m "initial"

git checkout -b a
echo "a" > a
git add .
git commit -m "a"

git checkout master; git checkout -b b
echo "b" > b
git add .
git commit -m "b"

git checkout master; git checkout -b c
echo "c" > c
git add .
git commit -m "c"

git checkout master

git merge master a b c -m "merge"
```

Adding `\-` and `\.` to the `syn match agitTree` seems to solve the problem, but not quite sure if this breaks anything.

**Comment by cohama** [comment]
Thank you!
