### ISSUE TITLE
AgitDiff is broken since 1056d84 (with fugitive)

### ISSUE THREAD

**Issue by wonderful-panda** [cohama/agit.vim#68]
1056d84の変更によって、staged/unstagedに対するAgitDiffが動かなくなりました。

fugitiveが入っていると、index上のファイルを表示するのにfugitiveを使いますが、

`fugitive://リポジトリのフルパス///0/リポジトリ内でのファイルの相対パス` となるはずのパスが
`fugitive://リポジトリのフルパス///0/ファイルのフルパス` となっています。

もしかするとWindows特有の問題かもしれません。

**Comment by wonderful-panda** [comment]
また、agit-statバッファでカーソル下のファイルのdiffを表示するケースだと、リポジトリルート以外がカレントディレクトリの場合常に失敗します。

**Comment by cohama** [comment]
報告ありがとうございました。

`-C` を使うようにした関係で `リポジトリのフルパス.git` の `.git` がなくなっていたのが原因でした

**Comment by cohama** [comment]
agit-stat の方は完全に関係ないチョンボでしたが...。
