### ISSUE TITLE
`vimproc#get_command_name: File "cd" is not found` occured on some linux envs

### ISSUE THREAD

**Issue by kentac55** [cohama/agit.vim#78]
https://github.com/cohama/agit.vim/commit/477d49af31f8b0b464bd24deaa154f6ab5f89a4c の変更にて`vimproc#get_command_name`からcdを呼び出していますが、一部のLinuxディストリビューションでは `$PATH/cd` が存在しない為、エラーが出ます。

```
[vimproc] vimproc#get_command_name: File "cd" is not found.
Error detected while processing function agit#launch[29]..agit#bufwin#agit_tabnew[6]..316[2]..318[1]..319[8]..304[10]..agit#aligner#align:
line    1:
E684: list index out of range: 0
E116: Invalid arguments for function len
E15: Invalid expression: len(a:table[0]) " sampling head's column number
```
確認したところMacOSやRHEL(確認したものはCent7, Fedora29)系には`/usr/bin/cd`がありそうでしたが、Ubuntu18.04とArch Linuxには存在しませんでした(shellのビルトインコマンドを使っているようです)。

ワークアラウンドとして動くディストロと同様の下記のようなものを$PATH/cdとして保存し`chmod +x`することで動きます。
```
#!/usr/bin/sh
builtin cd "$@"
```
windows環境での修正PR(#77)を適用してもこの問題は解決しません。

**Comment by cohama** [comment]
報告ありがとうございます。影響が大きそうだったので一旦 #75 を revert することにします。
その場合古い Git だと動かなくなりますが...

I decided to revert #75 because this problem affects a lot of environment.
